### ISSUE TITLE
Invalid descriptor for property '0'

### ISSUE THREAD

**Issue by DullReferenceException** [JakeChampion/polyfill-library#115]
In IE 11, I'm getting the error:

> Invalid descriptor for property '0'

Walking up the call stack, it's stemming from some code that is constructing a `DOMTokenList` with a body element and `'className'`:

```js
e=new DOMTokenList(body, 'className');
```

...which eventually hits this code which throws the error:

```js
_(y,n,r)
```

* `_` is some function named `defineProperty`
* `y` is some object
* `n` is `0`
* `r` is set to `undefined`

I'm using this polyfill URL (linebreaks added for readability):

```
https://cdn.polyfill.io/v2/polyfill.min.js
  ?unknown=polyfill
  &features=
    default%2C
    fetch%2C
    Array.prototype.%40%40iterator%2C
    Array.prototype.find%2C
    Array.prototype.findIndex%2C
    Function.name%2C
    Number.isFinite%2C
    Promise%2C
    String.prototype.repeat%2C
    Array.prototype.includes%2C
    Intl.~locale.en-US%2C
    Promise.prototype.finally
```

**Comment by nickwaelkens** [comment]
Using in combination with Next.js, also bumping on this issue. Any real workaround?

**Comment by JakeChampion** [comment]
Is someone able to create a small reproducible test case (on https://jsbin.com or similar) for me to work with?

**Comment by craigkovatch** [comment]
@JakeChampion Also seeing this, . I am unable to create a repro on jsbin because repro involves a giant IE11 polyfill file. However, I am generating that file like this:

```
const ie11_es6_opts = {
  uaString: 'Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko',
  minify: false,
  features: {
    'es6': { flags: ['gated'] }
  }
};

const devStream = fs.createWriteStream('polyfill-ie11-es6.js');
polyfillLibrary.getPolyfillString(ie11_es6_opts).then(bundleString => {
  devStream.write(bundleString);
  devStream.close();
});
```
Including that file in a barebones HTML file, opening the console, and referencing `Object.assign` (without even invoking it) yields the error:

![image](https://user-images.githubusercontent.com/10970257/56237437-d806ab80-6040-11e9-8f77-1a61995b5c1e.png)

**Comment by neenhouse** [comment]
We're running into this issue as well trying to use a minimal polyfill webpack configuration and allow run-time polyfills to patch our application.  Any movement on this issue in the last 30 days?

**Comment by HenriqueLimas** [comment]
I am getting this issue on Chrome 37 too. (It could be easier to debug than IE11). 
I got this error when trying to define a property using symbol.

```js
// Using native defineProperty from chrome
defineProperty({}, '__symbol:toStringTag0.327126665739342575', { value: 'Module' })
// { '[object Object]': [Exception: TypeError] }

// Using Object.defineProperty from the polyfill 
Object.defineProperty({}, '__symbol:toStringTag0.327126665739342575', { value: 'Module' })
// 'TypeError: Property description must be an object: undefined'
```

What is strange is that if I use anything different than the random number it will work. Like removing the last number, or use `6` at the end instead of `5`- '__symbol:toStringTag0.327126665739342576'. Also if I refresh the page it will work because the random number is different. I am getting this error using webpack + React Universal Component in dev mode. I am trying to find a more basic example to simulate the error on jsbin. Maybe you have some idea based on that example.
I would guess that what is happening is that it is trying to define a property with toStringTag key that is not configurable.

**Comment by HenriqueLimas** [comment]
With this code is possible to simulate on IE11 or also Chrome 37 (Before Symbol support) since it is easier to debug on Chrome:

```js
delete Object.prototype[Symbol.toStringTag] // At some point the prototype key is being deleted

try {
  var a = {}
  Object.defineProperty(a, Symbol.toStringTag, { value: 42 })
} catch (error) {
  console.log('Ops error', error);  // "Property description must be an object: undefined"
}

console.log(a[Symbol.toStringTag]) // 42
console.log(a.propertyIsEnumerable(Symbol.toStringTag))
// Cannot read property '@@__symbol:toStringTag0.85429089097306135' of undefined 
```

At some point the key `Symbol.toStringTag` in the Object.prototype is being deleted. I am having this issue using Webpack + ReactUniversalComponent in dev mode.

**Comment by felipetoffolo1** [comment]
Does anyone has any workaround for that?
I started having the same problem when using loadablecomponents.
For some reason this does not happen when  i run it locally.

**Comment by jbach** [comment]
What’s the status here? Breaking IE11 isn’t that useful for a polyfill lib…

**Comment by chr1s1k** [comment]
I had the same issue and fixed it by providing polyfill for `Object.getOwnPropertyDescriptors` coming from ES2017 (ES8) features.

`https://polyfill.io/v3/polyfill.min.js?features=Object.getOwnPropertyDescriptors`

**Comment by JakeChampion** [comment]
Is this still an issue people are seeing?

**Comment by leem32** [comment]
Yep, still an issue for me.

![Image of ie11 error](https://i.ibb.co/9snnKZ2/pollyfill-error.png)

**Comment by romainmenke** [comment]
Does the error happen simply by loading the polyfills on a blank page or is there surrounding code?
If there is extra code, can you share the url where this happens?

**Comment by leem32** [comment]
No, it does not happen on a blank page.
The page with issues is only in the local environment at the moment.

I will try adding more polyfills to the bundle and let you know if I work anything out.

**Comment by romainmenke** [comment]
@leem32 Thank you
Any example you could share with the error would be great.

>The page with issues is only in the local environment at the moment.

Is this something that could be made public in some form?

**Comment by romainmenke** [comment]
I was able to replicate this when using both `core-js` (through babel `preset-env`) and `polyfill.io`.

Excluding `web.dom-collections.iterator` and `web.dom-collections.for-each` in your babel config might help. [example](https://github.com/mrhenry/core-web-example-script-tag/pull/1/commits/b58b9a31f735f99ec341cb6fe18c0aff69b5f43d)

But `core-js` and `polyfill.io` have other conflicts so you will likely get other errors even if you exclude those.

**Comment by thienanle** [comment]
I was able to replicate this by loading this up in IE11 after adding the polyfill below:

https://moment.github.io/luxon/demo/global.html

Polyfill:
```
<script src="https://cdn.polyfill.io/v3/polyfill.js?features=default,String.prototype.repeat,Object.getOwnPropertyDescriptors,Array.prototype.find,Array.prototype.findIndex,Math.trunc,Math.sign,Object.is"></script>
```

<img width="1020" alt="image" src="https://user-images.githubusercontent.com/874402/145908383-2fa40656-59d0-4f6d-a812-549c5a320e29.png">
