### ISSUE TITLE
IntersectionObserver polyfills not being served to Desktop+Mobile Safari >16.1

### ISSUE THREAD

**Issue by mq2thez** [JakeChampion/polyfill-library#1255]
Hey folks, as part of this issue: https://github.com/Financial-Times/polyfill-library/issues/1192

This PR by @romainmenke was merged: https://github.com/Financial-Times/polyfill-library/pull/1231/files

I've just noticed during a deploy that with the release of Safari 16.1, we're back to seeing a significant spike in errors.

Would it be possible to update the numbers so that it serves for all versions of Safari until 17? I hate having to keep bothering folks every time Safari does a minor version bump.

**Comment by mq2thez** [comment]
@romainmenke in the last 14 days (which is as much data as I can easily access), we've been averaging 1k events per day. The spread is much more "Mobile Safari" than "Safari", but that lines up with our overall usage by browser. A random sample of several UA strings from events in the last hour:

```
Mozilla/5.0 (iPhone; CPU iPhone OS 16_1_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Mobile/15E148 Safari/604.1
```

```
Mozilla/5.0 (iPhone; CPU iPhone OS 16_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Mobile/15E148 Safari/604.1
```

```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15
```

According to Sentry, it looks like maybe ~350 of the 1k events in the last 24 hours are from a device showing up as a Mac (assumed to be an iPad), which vaguely lines up with our usage numbers. It seems like _maybe_ the number of errors is fewer, but since it's only coming from Safari 16.1.x and 16.2.x (whereas the previous numbers included errors from versions as far down as v13) I don't know that we can conclusively say that it has decreased.

**Comment by romainmenke** [comment]
@mq2thez We have just released version `4.6.0` that sets the Safari version for `IntersectionObserver` to `<17.0`.

Hopefully the underlying issue will be resolved before then 🤞

**Comment by mq2thez** [comment]
Thank you!

**Comment by romainmenke** [comment]
Safari 17 has been out for a while and given that no new issues have been reported I am assuming that it is now really fixed 🤞
