### ISSUE TITLE
Ungated Object.defineProperty breaks Vite's legacy output

### ISSUE THREAD

**Issue by lucasavila00** [JakeChampion/polyfill-library#1295]
### Describe the bug

I don't know if I should report this bug to Polyfill.io or Vite. Please pardon me if this should not have been written here.

I'm building a website that needs to run on IE11. I'm using `@vitejs/plugin-legacy` for it.

If I load the Intersection Observer polyfill from polyfill.io, the legacy code Vite built doesn't work. (The error "System is undefined" seems to mean SytemJS doesn't work, and the client-side app doesn't load)

![image](https://github.com/Financial-Times/polyfill-service/assets/12750442/b8300c45-8314-49b6-a890-d39315e32b0a)

I tried searching around and debugging it but this is as much information as I could get.

On the reproduction, the important parts are:

- Loading the polyfill https://github.com/lucasavila00/vite-polyfill-ie11/blob/main/index.html#L8
- The polyfill https://github.com/lucasavila00/vite-polyfill-ie11/blob/main/public/polyfill.js
- Vite legacy config https://github.com/lucasavila00/vite-polyfill-ie11/blob/main/vite.config.ts#L8
- Async Vite bundle https://github.com/lucasavila00/vite-polyfill-ie11/blob/main/index.html#L12

The bug only happens if Polyfill.io code is loaded before Vite code loads. If the order is reversed, it works correctly:

![image](https://github.com/Financial-Times/polyfill-service/assets/12750442/d9b2f210-2545-4e58-a49c-059764ffbdd2)

If only one of the 2 scripts is loaded, it also works correctly.

The use-case of this website requires external JS to be loaded into my website.

I have verified that this Intersection Observer polyfill does not break Vite code: https://github.com/GoogleChromeLabs/intersection-observer but ideally my website should not break if external - non-adversary - JS is loaded.

### Reproduction

https://github.com/lucasavila00/vite-polyfill-ie11

### Steps to reproduce

`npm install` && `npm run build` && `cd dist` && `python -m http.server`

### System Info

```shell
System:
    OS: Linux 6.2 Pop!_OS 22.04 LTS
    CPU: (16) x64 AMD Ryzen 7 3800X 8-Core Processor
    Memory: 44.64 GB / 62.72 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.10 - ~/.npm-global/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
  Browsers:
    Chrome: 113.0.5672.126
    Firefox: 112.0
  npmPackages:
    @vitejs/plugin-legacy: ^4.0.4 => 4.0.4 
    vite: ^4.3.9 => 4.3.9
```

### Used Package Manager

npm

**Comment by JakeChampion** [comment]
I've transferred this issue to polyfill-library as it relates to a polyfill

**Comment by sapphi-red** [comment]
FYI I created a more minimal repro.
https://github.com/sapphi-red-repros/core-js-object-create-polyfill-io-repro

I guess there's a incompatibility between core-js.

**Comment by JakeChampion** [comment]
That makes sense, we don't support running core-js polyfills alongside polyfill-library polyfills
