### ISSUE TITLE
Two issues with Inert polyfill

### ISSUE THREAD

**Issue by CheloXL** [JakeChampion/polyfill-library#1307]
First issue (that I'm willing to fix): The polyfill is being served to any version of Edge. I see in config.toml `edge = "*"`, but I'm not sure if that means old-edge (pre-chromium version) or current edge. Directions are welcomed.

Second, and this looks to be solved (but I'm still getting old code on cdn.polyfill.io/v3, so maybe it's because the website doesn't have this library running), it's that the following code is being served:
```js
var inertManager = new InertManager(document);
if (!Element.prototype.hasOwnProperty('inert')) {
....
}
```
So, even if the browser supports inert (like in my case), the `InertManager` is being instantiated (and tries to add to the document styles some inline styles). On the code in this repository I see that the `inertManager` line is inside the `if`. Just wanted to be sure this will be solved in a near future.

**Comment by romainmenke** [comment]
Hi @CheloXL,

I think both issues have already been resolved, they just haven't been deployed to the hosted service yet.

Modern Edge, which is Chromium based is mapped to Chrome versions.

`edge = "*"` actually means any Edge version that is using the EdgeHTML engine.


-----

The second issue was resolved in https://github.com/JakeChampion/polyfill-library/pull/1201

-----

I could be overlooking something :)

But I think this is just a matter of waiting for a new version to be pushed to the hosted service.

**Comment by CheloXL** [comment]
Excelent, thanks!
