### ISSUE TITLE
Array.prototype.reverse Patch for iOS 12 Safari

### ISSUE THREAD

**Issue by hax** [JakeChampion/polyfill-library#25]
See https://stackoverflow.com/questions/52390368/array-state-will-be-cached-in-ios-12-safari-is-bug-or-feature for the bug report and analysis.

Here is the patch: https://github.com/fanmingfei/array-reverse-ios12

**Comment by mhassan1** [comment]
It looks like BrowserStack does not have Safari 12.0 (it only has 12.1), so it would be difficult to validate the fix.

**Comment by romainmenke** [comment]
Can we test that the patch has no adverse effect?
As far as I understand the issue and the patch this could be a low risk bug fix.

So maybe it is ok to add it even if we can not test that specific version in Browserstack?

-----

I think you can manually test in Safari 12.0 by choosing iOS and checking a few different devices. These have different iOS and different Safari versions.

I use this myself to check the version by visiting that url in multiple iOS Safari versions : https://ua-analyser.romainmenke-workers.workers.dev/

So it might be possible to manually confirm that the patch is needed and works.
From there we could use CI to verify that the patch doesn't break anything.

**Comment by mhassan1** [comment]
If I fire up `iPhone 8` in BrowserStack and load that URL, I see `ios_saf/12.0.0`, but if I load up the [test page](https://abelyao.github.io/others/ios12-safari-bug.html), the issue doesn't seem to replicate. I'm not sure what that means.

We don't have a polyfill for `Array.prototype.reverse`, so we would need to add one.

Also, the usage table doesn't show `Safari 12.0`: https://caniuse.com/usage-table
